### ISSUE TITLE
Installation issue with configure script

### ISSUE THREAD

**Issue by ajratner** [Cvedia/cvedia-cli#12]
Hi,

When I run `configure` as directed in the `README`, I get the following error:
```
checking for suffix of object files... configure: error: in `/usr/src/cvedia/cvedia-cli':
configure: error: cannot compute suffix of object files: cannot compile
```

Any ideas what's going on?

Thanks!
Alex

**Comment by zsek** [comment]
Hi Alex,

I have seen this issue before and it had to do with missing packages. Are you trying to compile cvedia-cli on Ubuntu 14.04?

Regards,
Zissis

**Comment by ajratner** [comment]
Hi Zissis,

Thanks for the response!  Yes I'm trying to install on Ubuntu 14.04; any tips / advice?

Thanks,
Alex

**Comment by zsek** [comment]
Hi Alex,

Normally cvedia-cli does not compile on Ubuntu 14.04 because it needs gcc-5.
If you still need to compile it under Ubuntu 14.04 and can not use the docker, here are the required steps for you. 
Please note that you will be installing gcc-5 which is not in the stable Ubuntu 14.04 distribution but can be found under test repo.

Changes to compile under Ubuntu 14.04:
- Install gcc 5
- Install libopenexr6 instead of libopenexr22
- Install specific version of tensorflow
- Minor patch in cvedia-cli source to compile with python 3.4

Here is a copy-paste process you can follow:

apt-get update
apt-get -y install autoconf build-essential cmake curl gawk git \
  hdf5-tools ibgtk2.0-dev libarchive-dev libavcodec-dev libavformat-dev \
  libcurl4-openssl-dev libdc1394-22-dev libglu1-mesa libgtkglext1 \
  libhdf5-serial-dev libhighgui-dev libilmbase-dev libjasper-dev \
  libjpeg-dev libleveldb-dev liblua5.2-dev libopencv-dev libopenexr6 \
  libopenexr-dev libpangox-1.0-0 libpng-dev libprotobuf-dev \
  libsnappy-dev libsqlite3-dev libssl-dev libswscale-dev libtbb-dev \
  libtiff-dev libtool libv4l-0 libv4lconvert0 libxmu6 libxt6 \
  lua5.2 lua-md5 pkg-config protobuf-compiler python3-h5py \
  python3-pip python3-pycurl python3-requests python-dev python-h5py \
  python-pycurl python-requests rsync unzip wget

mkdir -p /usr/src/cvedia/luarocks && cd /usr/src/cvedia/luarocks
wget http://luarocks.github.io/luarocks/releases/luarocks-2.4.2.tar.gz
tar xzf luarocks-2.4.2.tar.gz
cd /usr/src/cvedia/luarocks/luarocks-2.4.2
./configure --prefix=/usr
make build
make install
luarocks install serpent

pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl

apt-get -y install software-properties-common python-software-properties
add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update && apt-get -y install gcc-5 g++-5
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1 --slave /usr/bin/g++ g++ /usr/bin/g++-5

mkdir -p /usr/src/cvedia && cd /usr/src/cvedia
git clone https://github.com/Cvedia/cvedia-cli
cd /usr/src/cvedia/cvedia-cli
sed -i s/python3.5m-config/python3.4m-config/g configure.ac
ACLOCAL_PATH="/usr/src/cvedia/cvedia-cli" autoreconf -if
autoheader
aclocal
autoconf
automake
./configure
make -j 4
make install

NOTE: This was tested on a fresh Ubuntu 14.04 installation.

I hope this helps!

Regards,
Zissis

**Comment by ajratner** [comment]
Thanks!!
